export const CONST_WIDTH = 1024;
export const CONST_HEIGHT = 576;
export const TYPE_SET_IMAGE_SUCCESS = 'TYPE_SET_IMAGE_SUCCESS';
export const TYPE_SET_OVERLAY_SUCCESS = 'TYPE_SET_OVERLAY_SUCCESS';
export const TYPE_SET_CROPPED_SUCCESS = 'TYPE_SET_CROPPED_SUCCESS';
export const TYPE_GET_OVERLAY = 'TYPE_GET_OVERLAY';
export const TYPE_GET_IMAGE = 'TYPE_GET_IMAGE';
export const CONST_OVERLAY_URL = '/overlay.png';
